#!/usr/bin/perl

##############################################################
#  Author     : Peng Hu
#  Email      ：penghu41@gmail.com
#  Last Edited: 08/26/2020
##############################################################

use strict;
use warnings;
use Getopt::Long;
my %opt;


GetOptions (\%opt,"tsv:s","qual:i","help");

my $help=<<USAGE;
This script could extract T->C convertion tsv file which was generated by sam2tsv and then screen out the read name by defined quality score.

Usage: perl $0 -tsv sample.tsv -qual 26

USAGE

if ($opt{help} or keys %opt < 1) {
	print "$help\n";
	exit();
}

my $in = $opt{tsv};
my $qual = $opt{qual};

open (IN,$in) or die $!;
open (OUT,">${in}_q${qual}.tsv") or die $!;
#my $line= <IN>;
#print $line;
while (my$line=<IN>) {
	chomp $line;
	my @array = split "\t",$line;
	if ($array[8] =~/(M|=|X)/) {
#		if ($array[4] =~ /C/ && $array[7] =~ /T/) {
                        if (ord($array[5])-33 > $qual) {
			    print OUT $line,"\t",ord($array[5])-33,"\n";
                        }
#		}
	}
}
close IN;

